### ISSUE TITLE
XMLDOM vulnerabilities

### ISSUE THREAD

**Issue by ABHINAVKR** [axelpale/filterxml#2]
**xmldom  ***
Severity: critical
Misinterpretation of malicious XML input - https://github.com/advisories/GHSA-h6q6-9hqw-rwfv
xmldom allows multiple root nodes in a DOM - https://github.com/advisories/GHSA-crh6-fp67-6883
Misinterpretation of malicious XML input - https://github.com/advisories/GHSA-5fg8-2547-mr8q
No fix available
**node_modules/xmldom**
  filterxml  *
  Depends on vulnerable versions of xmldom

xmldom has critical vulnerabilities, Can we move the dependency to the new version
Please check issue for reference - https://github.com/videojs/mpd-parser/issues/143
It's fixed into new library version - https://github.com/xmldom/xmldom/issues/271

**Comment by ABHINAVKR** [comment]
@axelpale  Can you please review  and merge the PR

**Comment by axelpale** [comment]
Thanks for pointing this out and providing a PR. I try to gather time to review the PR in the upcoming days.

**Comment by ABHINAVKR** [comment]
@axelpale  did you get chance to look into this PR?
 Please help in fixing the vulnerability

**Comment by axelpale** [comment]
Released the fix today in v1.1.5. I might proceed to v2.0.0 to upgrade other dependencies too.

**Comment by ABHINAVKR** [comment]
@axelpale Thanks a lot for fixing this
